#!/bin/bash

# Enable simple aliases to be sudo'ed. ("sudone"?)
# http://www.gnu.org/software/bash/manual/bashref.html#Aliases says: "If the
# last character of the alias value is a space or tab character, then the next
# command word following the alias is also checked for alias expansion."
alias sudo='sudo ';

# Easier folder navigation.
alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."
alias .....="cd ../../../.."

# I <3 u cask.
alias cask='brew cask'

# Be nice!
alias please=sudo

# Shortcut to edit hosts file.
alias hosts='sudo $EDITOR /etc/hosts'

# Confirm before overwriting
# I know it is bad practice to override the default commands, but this is for
# my own safety. If you really want the original "instakill" versions, you can
# use "command rm", "\rm", or "/bin/rm" inside your own commands, aliases, or
# shell functions. Note that separate scripts are not affected by the aliases
# defined here.
#alias cp='cp -i';
#alias mv='mv -i';
#alias rm='rm -i';

# List only directories
alias lsd="ls -lF | grep --color=never '^d'"

# Always use colour output for "ls".
# @TODO function to check os? or get rid of if entirely and go all mac?
if [[ "$OSTYPE" =~ ^darwin ]]; then
  alias ls='command ls -G';
else
  alias ls='command ls --color=auto';
fi;

# Stopwatch
alias timer='echo "Timer started. Stop with Ctrl-D." && date && time cat && date'

# Get OS X Software Updates, update installed Ruby gems, Homebrew, npm, and their
# installed packages.
alias update='sudo softwareupdate -i -a; brew update; brew upgrade; brew cleanup; npm update npm -g; npm update -g; sudo gem update --system; sudo gem update'

# What's my IP address.
alias ip="dig +short myip.opendns.com @resolver1.opendns.com"

# OS X has no `md5sum`, so use `md5` as a fallback
command -v md5sum > /dev/null || alias md5sum="md5"

# OS X has no `sha1sum`, so use `shasum` as a fallback
command -v sha1sum > /dev/null || alias sha1sum="shasum"

# Empty the Trash on all mounted volumes and the main HDD. Also, clear Apple’s
# System Logs to improve shell startup speed
alias emptytrash="sudo rm -rfv /Volumes/*/.Trashes; sudo rm -rfv ~/.Trash; sudo rm -rfv /private/var/log/asl/*.asl"

# Show/hide hidden files in Finder.
alias show="defaults write com.apple.finder AppleShowAllFiles -bool true && killall Finder"
alias hide="defaults write com.apple.finder AppleShowAllFiles -bool false && killall Finder"

# Hide/show all desktop icons.
alias hidedesktop="defaults write com.apple.finder CreateDesktop -bool false && killall Finder"
alias showdesktop="defaults write com.apple.finder CreateDesktop -bool true && killall Finder"

# Kill all the tabs in Chrome to free up memory.
# [C] explained: http://www.commandlinefu.com/commands/view/402/exclude-grep-from-your-grepped-output-of-ps-alias-included-in-description
alias chromekill="ps ux | grep '[C]hrome Helper --type=renderer' | grep -v extension-process | tr -s ' ' | cut -d ' ' -f2 | xargs kill"

# Lock the screen (when going AFK).
alias afk="/System/Library/CoreServices/Menu\ Extras/User.menu/Contents/Resources/CGSession -suspend"

# Open with Photoshop.
alias photoshop='open -a "Adobe Photoshop CS6"'

# Open Chrome Canary with web security disabled to overcome CORS issues for local dev.
alias corsdev="open -n -a /opt/homebrew-cask/Caskroom/google-chrome-canary/latest/Google\ Chrome\ Canary.app/Contents/MacOS/Google\ Chrome\ Canary --args --disable-web-security"

# Create a new MySQL database.
alias mc="mysql-create.sh"

### DRUPAL STUFF ###
# @TODO clean this up! :)

# Drush uninstall.
alias dun="drush pm-uninstall"

# PHP Code Sniffer for Drupal.
# This requires Composer and the Drupal "Coder" module.
alias codercs="phpcs --standard=~/.composer/vendor/drupal/coder/coder_sniffer/Drupal/ --extensions=php,module,inc,install,test,profile,theme --encoding=utf-8"

# PHP Code Sniffer for Drupal - Bluetent version.
alias btcs="phpcs --standard=~/Bluetent/code-sniffer/Drupal --extensions=php,module,inc,install,test,profile,theme,js,sass,scss --encoding=utf-8"

# Run simpletest from the terminal in a Drupal 7 site root.
alias simpletest="php scripts/run-tests.sh --color --verbose"

# Drupal 7.
export PATH=/Applications/MAMP/bin/php/php5.3.29/bin:$PATH
export DRUSH_PHP=/Applications/MAMP/bin/php/php5.3.29/bin/php

# Drupal 8.
#export PATH=/Applications/MAMP/bin/php/php5.4.33/bin:$PATH
#export DRUSH_PHP=/Applications/MAMP/bin/php/php5.4.33/bin/php

# Drush for Drupal 8 (git clone - no official release yet)
alias d8='DRUSH_PHP=/Applications/MAMP/bin/php/php5.4.33/bin/php ~/Projects/drupal8/drush/drush'

# PHP 5.4 for Drupal 8 in the command line.
alias php54='/Applications/MAMP/bin/php/php5.4.33/bin/php'

# @TODO drush autocomplete!
# @TODO setup pear stuff
# @TODO cleanup Drupal 7 vs 8 stuff (var for php minor versions to sub in multiple places seamlessly?)
